package resolver

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func GenerateArtifacts(resolution Resolution) (Artifacts, error) {
	if err := VerifyResolution(resolution); err != nil {
		return Artifacts{}, err
	}
	linked := []string{
		"gooo linked semantic_meta_package_resolver v1",
		"root name=" + resolution.Root,
		"status state=" + string(resolution.Status),
		"contract digest=" + resolution.ContractDigest,
		"catalog digest=" + resolution.CatalogDigest,
		"lock digest=" + resolution.Lock.LockDigest,
	}
	for _, pkg := range resolution.Packages {
		linked = append(linked, fmt.Sprintf("package name=%s version=%s digest=%s source_digest=%s semantic_id=%s stage=%s owner=%s", pkg.Name, pkg.Version, pkg.Digest, pkg.SourceDigest, pkg.SemanticID, pkg.Stage, pkg.OriginOwner))
	}
	for _, edge := range resolution.Edges {
		linked = append(linked, fmt.Sprintf("edge from=%s to=%s constraint=%s semantic_id=%s type=%s stage=%s", edge.From, edge.To, edge.Constraint, edge.SemanticID, edge.Type, edge.Stage))
	}
	linkedGooo := []byte(strings.Join(linked, "\n") + "\n")

	ir := LinkedIR{Schema: IRSchema, Version: "v1", Root: resolution.Root, Status: resolution.Status, Claim: resolution.Claim, ContractDigest: resolution.ContractDigest, CatalogDigest: resolution.CatalogDigest, LockDigest: resolution.Lock.LockDigest, Packages: resolution.Packages, Edges: resolution.Edges}
	irDigest, err := digestValue(ir)
	if err != nil {
		return Artifacts{}, err
	}
	ir.IRDigest = irDigest
	irBytes, err := marshalJSON(ir)
	if err != nil {
		return Artifacts{}, err
	}
	goBytes := []byte(generateGoArtifact(resolution, irDigest))
	artifactDigest := digestBytes(goBytes)
	lockBytes, err := marshalJSON(resolution.Lock)
	if err != nil {
		return Artifacts{}, err
	}
	resolutionBytes, err := marshalJSON(resolution)
	if err != nil {
		return Artifacts{}, err
	}
	manifest := struct {
		Schema         string `json:"schema"`
		Status         Status `json:"status"`
		ContractDigest string `json:"contract_digest"`
		CatalogDigest  string `json:"catalog_digest"`
		LockDigest     string `json:"lock_digest"`
		IRDigest       string `json:"ir_digest"`
		ArtifactDigest string `json:"artifact_digest"`
		Files          []struct {
			Path   string `json:"path"`
			Digest string `json:"digest"`
			Bytes  int    `json:"bytes"`
		} `json:"files"`
	}{Schema: ArtifactSchema, Status: resolution.Status, ContractDigest: resolution.ContractDigest, CatalogDigest: resolution.CatalogDigest, LockDigest: resolution.Lock.LockDigest, IRDigest: irDigest, ArtifactDigest: artifactDigest}
	manifest.Files = []struct {
		Path   string `json:"path"`
		Digest string `json:"digest"`
		Bytes  int    `json:"bytes"`
	}{
		{Path: "linked.gooo", Digest: digestBytes(linkedGooo), Bytes: len(linkedGooo)},
		{Path: "linked-ir.json", Digest: digestBytes(irBytes), Bytes: len(irBytes)},
		{Path: "linked-artifact.go", Digest: artifactDigest, Bytes: len(goBytes)},
		{Path: "gooo.lock.json", Digest: digestBytes(lockBytes), Bytes: len(lockBytes)},
		{Path: "resolution.json", Digest: digestBytes(resolutionBytes), Bytes: len(resolutionBytes)},
	}
	manifestBytes, err := marshalJSON(manifest)
	if err != nil {
		return Artifacts{}, err
	}
	return Artifacts{LinkedGooo: linkedGooo, IR: irBytes, Go: goBytes, Lock: lockBytes, Resolution: resolutionBytes, Manifest: manifestBytes, ArtifactDigest: artifactDigest, IRDigest: irDigest, LockDigest: resolution.Lock.LockDigest}, nil
}

func marshalJSON(value any) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// MarshalJSONForCLI keeps command output on the same deterministic encoding
// path as the generated wire artifacts.
func MarshalJSONForCLI(value any) ([]byte, error) { return marshalJSON(value) }

func generateGoArtifact(resolution Resolution, irDigest string) string {
	selected := append([]PackageLock(nil), resolution.Packages...)
	sort.Slice(selected, func(i, j int) bool { return selected[i].Name < selected[j].Name })
	payload := struct {
		Schema     string        `json:"schema"`
		Status     Status        `json:"status"`
		Root       string        `json:"root"`
		LockDigest string        `json:"lock_digest"`
		IRDigest   string        `json:"ir_digest"`
		Packages   []PackageLock `json:"packages"`
	}{ArtifactSchema, resolution.Status, resolution.Root, resolution.Lock.LockDigest, irDigest, selected}
	data, _ := json.Marshal(payload)
	return fmt.Sprintf("// Code generated by gooo semantic meta package resolver; DO NOT EDIT.\npackage main\n\nimport \"fmt\"\n\nconst LinkedArtifactSchema = %q\nconst LinkedArtifactDigestBasis = %q\n\nfunc main() {\n\tfmt.Println(%q)\n}\n", ArtifactSchema, irDigest, string(data))
}

func WriteArtifacts(out string, artifacts Artifacts) error {
	if !filepath.IsAbs(out) {
		return fmt.Errorf("output directory must be an absolute caller-owned path")
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	files := map[string][]byte{
		"linked.gooo":        artifacts.LinkedGooo,
		"linked-ir.json":     artifacts.IR,
		"linked-artifact.go": artifacts.Go,
		"gooo.lock.json":     artifacts.Lock,
		"resolution.json":    artifacts.Resolution,
		"manifest.json":      artifacts.Manifest,
	}
	paths := make([]string, 0, len(files))
	for name := range files {
		paths = append(paths, name)
	}
	sort.Strings(paths)
	for _, name := range paths {
		if err := os.WriteFile(filepath.Join(out, name), files[name], 0o644); err != nil {
			return err
		}
	}
	return nil
}

func ExecuteArtifact(path string) (Execution, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Execution{}, err
	}
	artifactDigest := digestBytes(data)
	if !strings.Contains(string(data), "const LinkedArtifactSchema") || !strings.Contains(string(data), ArtifactSchema) {
		return Execution{}, fmt.Errorf("generated artifact schema marker missing")
	}
	cmd := exec.Command("go", "run", path)
	cmd.Dir = filepath.Dir(path)
	cmd.Env = append(os.Environ(), "GO111MODULE=off")
	output, err := cmd.Output()
	if err != nil {
		return Execution{}, fmt.Errorf("execute generated artifact: %w", err)
	}
	output = []byte(strings.TrimSpace(string(output)))
	var payload map[string]any
	if err := json.Unmarshal(output, &payload); err != nil {
		return Execution{}, fmt.Errorf("generated artifact output is not JSON: %w", err)
	}
	if payload["schema"] != ArtifactSchema {
		return Execution{}, fmt.Errorf("generated artifact returned an unexpected schema")
	}
	return Execution{Schema: ExecutionSchema, Status: Closed, ArtifactDigest: artifactDigest, OutputDigest: digestBytes(output), Output: string(output)}, nil
}
